version : '3.7'
services:
    database:
        image: mysql:5.7
        container_name: sqldb
        env_file: 
            - ./App/.env
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - backend
        volumes:
            - my-db:/var/lib/mysql
    app:
        container_name: go_api
        build:
            context: ./App
        ports:
            - "8000:8000"
        networks:
            - frontend
            - backend
        depends_on:
            - database
    frontend:
        container_name: front_end
        build: 
            context: ./FE
        ports:
            - 5000:80
        networks:
            - frontend
        depends_on:
            - database
            - app
networks:
    frontend:
    backend:
volumes:
  my-db:
